language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo dpkg -L python-opencv
install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - py.test